### ISSUE TITLE
Testset missing

### ISSUE THREAD

**Issue by zijunwei** [gyglim/video2gif_dataset#3]
Hi dear Dr. Gygli,
The test set link you provided  https://data.vision.ee.ethz.ch/cvl/video2gif/YouTubeID.mp4 is unreachable now. Could you please update?
Thanks!

**Comment by gyglim** [comment]
That just defines the pattern. You need to replace `YouTubeID` with the IDs provided in https://github.com/gyglim/video2gif_dataset/blob/master/testset.txt
