### ISSUE TITLE
Can you tell me how to get the SumMe dataset?

### ISSUE THREAD

**Issue by JKANG94** [gyglim/video2gif_dataset#4]
Can you tell me how to get the SumMe dataset?

**Comment by gyglim** [comment]
https://gyglim.github.io/me/vsum/index.html#benchmark

**Comment by neerajmoitra08** [comment]
This link is showing "site not found", any other way to get access of this dataset?

**Comment by gyglim** [comment]
fixed again

**Comment by ZitingLi** [comment]
Sorry for the inconvenience, but it seems that the link above is not working. May I ask if there is another way to access the dataset? Thank you!

**Comment by gyglim** [comment]
> Sorry for the inconvenience, but it seems that the link above is not working. May I ask if there is another way to access the dataset? Thank you!

You can find it here:
https://data.vision.ee.ethz.ch/cvl/SumMe/SumMe.zip

The zip contains the following:
```
demo.m File that shows how to evaluate your summary
GT/ folder containing the human summary selections
videos/ folder with the videos themselves in webm and mp4 (H.264) format
matlab/ code for the evaluation including plotting
python/ basic code for evaluating in python (needs scipy, numpy, matplotlib)
to run the python demo call (from the dataset root):
python python/demo.py
```
