### ISSUE TITLE
GIFs links are not available

### ISSUE THREAD

**Issue by yeliudev** [gyglim/video2gif_dataset#9]
@gyglim Thanks for your work! The links to the GIFs in metadata are not available now. May I ask that where can I find these GIFs?

**Comment by gyglim** [comment]
The source website is no longer available. But you can regenerate the GIFs from the video. The youtube ID and the start and and time in that video is stored in the metadata.txt
Let me know if this doesn't work for you

**Comment by yeliudev** [comment]
I see. Thanks for your reply!
